sudo: required
services:
  - docker

before_install:
  - docker build -t akiraspeirs/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run akiraspeirs/react-test npm test -- --coverage

after_success:
  - docker build -t akiraspeirs/multi-client ./frontend
  - docker build -t akiraspeirs/multi-nginx ./nginx
  - docker build -t akiraspeirs/multi-server ./server
  - docker build -t akiraspeirs/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  # Take those images and push to Docker Hub
  - docker push akiraspeirs/multi-client
  - docker push akiraspeirs/multi-nginx
  - docker push akiraspeirs/multi-server
  - docker push akiraspeirs/multi-worker